# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85858a136d35750616168d35526acc2a889cc521b24f594f12c292ea8105ef65486cb013646f015e79dfca2b32f6d28e9986f415303da1376d6e0343181ea307

test:
  secret_key_base: 67fd56b605834f87db4bf92dcd8bdb6b7064487e57a698b0fbf7c5a26709fd89411ffbef462434c95483725bd9134cf3f5e5a08f79fc38560cb2b8d00da9d183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
